// MarkdownArticle — Code component template for rendering CMS articles and Markdown content.
// Built cleanly with line-array join to eliminate nested template-literal and regex escaping errors.

const parts = [
  "'use client';",
  "",
  '/** @label "Markdown Article" */',
  '/** @comment "Renders formatted articles with customizable typography from CMS Markdown or custom text" */',
  '/** @defaultWidth 760 */',
  '/** @defaultHeight 600 */',
  '/** @controls {',
  '  "content": { "type": "text", "label": "Article Content (Markdown)", "default": "# Main Article\\n\\n### Subtitle\\n\\nSample article with **bold** text and [links](https://example.com)." },',
  '  "baseSize": { "type": "number", "label": "Base Font Size (px)", "min": 12, "max": 28, "default": 16, "step": 1 },',
  '  "headingFont": { "type": "font", "label": "Heading Font", "default": "Inter, sans-serif" },',
  '  "bodyFont": { "type": "font", "label": "Body Font", "default": "Inter, sans-serif" },',
  '  "headingColor": { "type": "color", "label": "Heading Color", "default": "#ffffff" },',
  '  "textColor": { "type": "color", "label": "Body Text Color", "default": "#a1a1aa" },',
  '  "accentColor": { "type": "color", "label": "Accent / Link Color", "default": "#eab308" },',
  '  "h3Color": { "type": "color", "label": "H3 Override Color (Optional)", "default": "" },',
  '  "lineHeight": { "type": "number", "label": "Line Height", "min": 1.2, "max": 2.5, "default": 1.75, "step": 0.05 },',
  '  "maxWidth": { "type": "number", "label": "Max Width (px)", "min": 320, "max": 1400, "default": 760, "step": 10 }',
  '} */',
  '',
  "import React, { useMemo } from 'react';",
  "import { withResponsiveProps } from '@revyme/runtime';",
  '',
  "const DEFAULT_SAMPLE_CONTENT = [",
  "  '# Main Article Title',",
  "  '',",
  "  '### Subtitle or Section',",
  "  '',",
  "  'This is a formatted paragraph with **bold text**, *italic*, and a [link](https://example.com).',",
  "  '',",
  "  '> This is an important quote or highlight from the author.',",
  "  '',",
  "  '* First bullet point',",
  "  '* Second bullet point',",
  "  '',",
  "  '### Second Subtitle',",
  "  '',",
  "  'Another paragraph with detailed information.'",
  "].join(String.fromCharCode(10));",
  '',
  'function renderInline(text, accentColor, headingColor) {',
  '  const parts = [];',
  '  let cur = text;',
  '  let key = 0;',
  '  while (cur.length > 0) {',
  '    if (cur.startsWith("[") && cur.indexOf("](") > 0 && cur.indexOf(")") > cur.indexOf("](")) {',
  '      const closeBracket = cur.indexOf("](");',
  '      const closeParen = cur.indexOf(")", closeBracket);',
  '      const label = cur.slice(1, closeBracket);',
  '      const href = cur.slice(closeBracket + 2, closeParen);',
  '      parts.push(React.createElement("a", { key: key++, href, target: "_blank", rel: "noopener noreferrer", style: { color: accentColor, textDecoration: "underline", textUnderlineOffset: "3px", fontWeight: 500 } }, label));',
  '      cur = cur.slice(closeParen + 1);',
  '      continue;',
  '    }',
  '    if (cur.startsWith("**")) {',
  '      const endBold = cur.indexOf("**", 2);',
  '      if (endBold > 2) {',
  '        parts.push(React.createElement("strong", { key: key++, style: { color: headingColor, fontWeight: 700 } }, cur.slice(2, endBold)));',
  '        cur = cur.slice(endBold + 2);',
  '        continue;',
  '      }',
  '    }',
  '    if (cur.startsWith("*")) {',
  '      const endItalic = cur.indexOf("*", 1);',
  '      if (endItalic > 1) {',
  '        parts.push(React.createElement("em", { key: key++, style: { fontStyle: "italic", opacity: 0.9 } }, cur.slice(1, endItalic)));',
  '        cur = cur.slice(endItalic + 1);',
  '        continue;',
  '      }',
  '    }',
  '    const idxB = cur.indexOf("[");',
  '    const idxS = cur.indexOf("*");',
  '    let nextSpecial = -1;',
  '    if (idxB !== -1 && idxS !== -1) nextSpecial = Math.min(idxB, idxS);',
  '    else if (idxB !== -1) nextSpecial = idxB;',
  '    else nextSpecial = idxS;',
  '    if (nextSpecial === -1) { parts.push(cur); break; }',
  '    else if (nextSpecial === 0) { parts.push(cur[0]); cur = cur.slice(1); }',
  '    else { parts.push(cur.slice(0, nextSpecial)); cur = cur.slice(nextSpecial); }',
  '  }',
  '  return parts;',
  '}',
  '',
  'function MarkdownArticleComponent(props) {',
  '  const content = props.content;',
  '  const baseSize = props.baseSize || 16;',
  "  const headingFont = props.headingFont || 'Inter, sans-serif';",
  "  const bodyFont = props.bodyFont || 'Inter, sans-serif';",
  "  const headingColor = props.headingColor || '#ffffff';",
  "  const textColor = props.textColor || '#a1a1aa';",
  "  const accentColor = props.accentColor || '#eab308';",
  '  const h3Color = props.h3Color && props.h3Color.trim() ? props.h3Color.trim() : headingColor;',
  '  const lineHeight = props.lineHeight || 1.75;',
  '  const maxWidth = props.maxWidth || 760;',
  '',
  '  const rawText = (content != null && String(content).trim().length > 0) ? String(content) : DEFAULT_SAMPLE_CONTENT;',
  '',
  '  const blocks = useMemo(() => {',
  '    const lines = rawText.split(String.fromCharCode(10));',
  '    const result = [];',
  '    let currentList = null;',
  '    let blockIndex = 0;',
  '    const flushList = () => {',
  '      if (!currentList) return;',
  '      const Tag = currentList.type;',
  '      result.push(React.createElement(Tag, { key: "list-" + (blockIndex++), style: { margin: "0 0 " + (baseSize * 1.2) + "px 0", paddingLeft: baseSize * 1.5, color: textColor, lineHeight, fontSize: baseSize, fontFamily: bodyFont } }, currentList.items.map((item, idx) => React.createElement("li", { key: idx, style: { marginBottom: baseSize * 0.4 } }, renderInline(item, accentColor, headingColor)))));',
  '      currentList = null;',
  '    };',
  '    for (let i = 0; i < lines.length; i++) {',
  '      const line = lines[i].trim();',
  '      if (!line) { flushList(); continue; }',
  '      if (line === "---" || line === "***" || line === "___") {',
  '        flushList();',
  '        result.push(React.createElement("hr", { key: "hr-" + (blockIndex++), style: { border: "none", borderTop: "1px solid rgba(255,255,255,0.12)", margin: (baseSize * 2) + "px 0" } }));',
  '        continue;',
  '      }',
  '      if (line.startsWith("# ")) {',
  '        flushList();',
  '        result.push(React.createElement("h1", { key: "h1-" + (blockIndex++), style: { fontFamily: headingFont, fontSize: Math.round(baseSize * 2.2), color: headingColor, margin: (baseSize * 2.2) + "px 0 " + (baseSize * 0.8) + "px 0", lineHeight: 1.2 } }, renderInline(line.slice(2).trim(), accentColor, headingColor)));',
  '        continue;',
  '      }',
  '      if (line.startsWith("## ")) {',
  '        flushList();',
  '        result.push(React.createElement("h2", { key: "h2-" + (blockIndex++), style: { fontFamily: headingFont, fontSize: Math.round(baseSize * 1.75), color: headingColor, margin: (baseSize * 1.8) + "px 0 " + (baseSize * 0.7) + "px 0", lineHeight: 1.25 } }, renderInline(line.slice(3).trim(), accentColor, headingColor)));',
  '        continue;',
  '      }',
  '      if (line.startsWith("### ")) {',
  '        flushList();',
  '        result.push(React.createElement("h3", { key: "h3-" + (blockIndex++), style: { fontFamily: headingFont, fontSize: Math.round(baseSize * 1.35), color: h3Color, margin: (baseSize * 1.6) + "px 0 " + (baseSize * 0.7) + "px 0", lineHeight: 1.3 } }, renderInline(line.slice(4).trim(), accentColor, h3Color)));',
  '        continue;',
  '      }',
  '      if (line.startsWith("#### ")) {',
  '        flushList();',
  '        result.push(React.createElement("h4", { key: "h4-" + (blockIndex++), style: { fontFamily: headingFont, fontSize: Math.round(baseSize * 1.15), color: headingColor, margin: (baseSize * 1.3) + "px 0 " + (baseSize * 0.5) + "px 0", lineHeight: 1.35 } }, renderInline(line.slice(5).trim(), accentColor, headingColor)));',
  '        continue;',
  '      }',
  '      if (line.startsWith("> ")) {',
  '        flushList();',
  '        result.push(React.createElement("blockquote", { key: "quote-" + (blockIndex++), style: { borderLeft: "3px solid " + accentColor, paddingLeft: baseSize + "px", margin: baseSize + "px 0", fontStyle: "italic", color: textColor, opacity: 0.9, fontSize: Math.round(baseSize * 1.05), lineHeight, fontFamily: bodyFont } }, renderInline(line.slice(2).trim(), accentColor, headingColor)));',
  '        continue;',
  '      }',
  '      if (line.startsWith("* ") || line.startsWith("- ")) {',
  '        const itemText = line.slice(2);',
  '        if (!currentList || currentList.type !== "ul") { flushList(); currentList = { type: "ul", items: [itemText] }; }',
  '        else { currentList.items.push(itemText); }',
  '        continue;',
  '      }',
  '      const dotIdx = line.indexOf(". ");',
  '      if (dotIdx > 0 && !isNaN(Number(line.slice(0, dotIdx)))) {',
  '        const itemText = line.slice(dotIdx + 2);',
  '        if (!currentList || currentList.type !== "ol") { flushList(); currentList = { type: "ol", items: [itemText] }; }',
  '        else { currentList.items.push(itemText); }',
  '        continue;',
  '      }',
  '      flushList();',
  '      result.push(React.createElement("p", { key: "p-" + (blockIndex++), style: { fontFamily: bodyFont, fontSize: baseSize, color: textColor, lineHeight, margin: "0 0 " + (baseSize * 1.15) + "px 0" } }, renderInline(line, accentColor, headingColor)));',
  '    }',
  '    return result;',
  '  }, [rawText, baseSize, headingFont, bodyFont, headingColor, textColor, accentColor, h3Color, lineHeight]);',
  '',
  '  return React.createElement("article", Object.assign({ style: Object.assign({ boxSizing: "border-box", width: "100%", maxWidth: maxWidth ? maxWidth + "px" : "760px", margin: "0 auto", padding: "16px 0" }, props.style) }, props), blocks);',
  '}',
  '',
  'export default withResponsiveProps(MarkdownArticleComponent);',
];

export const MARKDOWN_ARTICLE_COMPONENT = parts.join('\\n');
